# Generated by Django 4.2.3 on 2023-07-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
